// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSSwrOLVWmFFcTGUyJvJBRG1_oaHAB5ao',
    appId: '1:685690685142:web:a2914fcb4877f5b6f22b77',
    messagingSenderId: '685690685142',
    projectId: 'my-shopping-list-web',
    authDomain: 'my-shopping-list-web.firebaseapp.com',
    storageBucket: 'my-shopping-list-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO9u34pcX0gSvz4PTZ3koxt4oaxPbzQBQ',
    appId: '1:685690685142:android:8f33384cd3ee8ee5f22b77',
    messagingSenderId: '685690685142',
    projectId: 'my-shopping-list-web',
    storageBucket: 'my-shopping-list-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZzF5ECywhwl0x7giwzmutoAQc3O5cZ4',
    appId: '1:685690685142:ios:84ce51f7399aa884f22b77',
    messagingSenderId: '685690685142',
    projectId: 'my-shopping-list-web',
    storageBucket: 'my-shopping-list-web.firebasestorage.app',
    iosClientId: '685690685142-6au01lfi55hm9fmf6bhrlqngtkck2fbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZzF5ECywhwl0x7giwzmutoAQc3O5cZ4',
    appId: '1:685690685142:ios:84ce51f7399aa884f22b77',
    messagingSenderId: '685690685142',
    projectId: 'my-shopping-list-web',
    storageBucket: 'my-shopping-list-web.firebasestorage.app',
    iosClientId: '685690685142-6au01lfi55hm9fmf6bhrlqngtkck2fbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myShoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSSwrOLVWmFFcTGUyJvJBRG1_oaHAB5ao',
    appId: '1:685690685142:web:6a7d3ba985f984a4f22b77',
    messagingSenderId: '685690685142',
    projectId: 'my-shopping-list-web',
    authDomain: 'my-shopping-list-web.firebaseapp.com',
    storageBucket: 'my-shopping-list-web.firebasestorage.app',
  );
}
